// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAU8DisBc3AUUKX7Ln8p6Q3DzC_3dzz-Y',
    appId: '1:490662866951:web:5043e8fef89f56dd33faa2',
    messagingSenderId: '490662866951',
    projectId: 'netflixclone-5a60e',
    authDomain: 'netflixclone-5a60e.firebaseapp.com',
    storageBucket: 'netflixclone-5a60e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw3Pe0S9UaP6Ok9VMXSt8l_nXFlCdIh4g',
    appId: '1:490662866951:android:bd3735e0cb721ab733faa2',
    messagingSenderId: '490662866951',
    projectId: 'netflixclone-5a60e',
    storageBucket: 'netflixclone-5a60e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGpcVWcmY_JjX8CpW4-hdrIXWnUKC5i8',
    appId: '1:490662866951:ios:0f7dba1215bde77033faa2',
    messagingSenderId: '490662866951',
    projectId: 'netflixclone-5a60e',
    storageBucket: 'netflixclone-5a60e.appspot.com',
    iosBundleId: 'com.example.netflixClonecode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpGpcVWcmY_JjX8CpW4-hdrIXWnUKC5i8',
    appId: '1:490662866951:ios:0f7dba1215bde77033faa2',
    messagingSenderId: '490662866951',
    projectId: 'netflixclone-5a60e',
    storageBucket: 'netflixclone-5a60e.appspot.com',
    iosBundleId: 'com.example.netflixClonecode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAU8DisBc3AUUKX7Ln8p6Q3DzC_3dzz-Y',
    appId: '1:490662866951:web:08545791cd0648f333faa2',
    messagingSenderId: '490662866951',
    projectId: 'netflixclone-5a60e',
    authDomain: 'netflixclone-5a60e.firebaseapp.com',
    storageBucket: 'netflixclone-5a60e.appspot.com',
  );
}
